// <auto-generated />
using System;
using CourtGo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourtGo.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CourtGoDbContext))]
    partial class CourtGoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourtGo.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte>("BookingStatus")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("CancellationPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CenterNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourtNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerEmailSnapshot")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CustomerNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerPhoneSnapshot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("CustomerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DepositAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DepositPercentSnapshot")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("HoldExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("PaymentStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("QrToken")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte>("Source")
                        .HasColumnType("tinyint");

                    b.Property<string>("SportNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BookingCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Bookings_BookingCode");

                    b.HasIndex("CancellationPolicyId");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_Bookings_CreatedByUser");

                    b.HasIndex("QrToken")
                        .IsUnique()
                        .HasDatabaseName("UX_Bookings_QrToken")
                        .HasFilter("([QrToken] IS NOT NULL)");

                    b.HasIndex("BookingStatus", "StartAt")
                        .HasDatabaseName("IX_Bookings_Status_StartAt");

                    b.HasIndex("CourtId", "StartAt")
                        .HasDatabaseName("IX_Bookings_Court_StartAt");

                    b.HasIndex("CustomerUserId", "StartAt")
                        .HasDatabaseName("IX_Bookings_Customer_StartAt");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.BookingPaymentSummary", b =>
                {
                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RemainingToCollect")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SuccessfulChargeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SuccessfulRefundAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView("vw_BookingPaymentSummary", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.BookingSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("HoldExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsOccupying")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PriceRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ReservationState")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("IX_BookingSlots_BookingId");

                    b.HasIndex("PriceRuleId");

                    b.HasIndex("CourtId", "StartAt")
                        .IsUnique()
                        .HasDatabaseName("UX_BookingSlots_ActiveCourtStart")
                        .HasFilter("([IsOccupying]=(1))");

                    b.HasIndex("CourtId", "StartAt", "EndAt")
                        .HasDatabaseName("IX_BookingSlots_Court_StartAt_EndAt");

                    b.ToTable("BookingSlots", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.BookingStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<byte?>("FromStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("ToStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("BookingId", "CreatedAt")
                        .HasDatabaseName("IX_BookingStatusHistories_Booking_CreatedAt");

                    b.ToTable("BookingStatusHistories", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.CancellationPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasDatabaseName("UX_CancellationPolicies_OneActive")
                        .HasFilter("([IsActive]=(1))");

                    b.HasIndex("Name", "Version")
                        .IsUnique()
                        .HasDatabaseName("UQ_CancellationPolicies_Name_Version");

                    b.ToTable("CancellationPolicies", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.CancellationPolicyRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CancellationPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MaxHoursBeforeStart")
                        .HasColumnType("int");

                    b.Property<int>("MinHoursBeforeStart")
                        .HasColumnType("int");

                    b.Property<decimal>("RefundPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CancellationPolicyId", "MinHoursBeforeStart")
                        .HasDatabaseName("IX_CancellationPolicyRules_Policy_MinHours");

                    b.ToTable("CancellationPolicyRules", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.CancellationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<decimal?>("ApprovedRefundAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CalculatedRefundAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ProcessedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("RequestSource")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedByUserId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("BookingId", "Status")
                        .HasDatabaseName("IX_CancellationRequests_Booking_Status");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_CancellationRequests_Status_CreatedAt");

                    b.ToTable("CancellationRequests", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.CheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CheckedInAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<byte>("Method")
                        .HasColumnType("tinyint");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("OutstandingPaymentOverride")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("StaffUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("UQ_CheckIns_BookingId");

                    b.HasIndex("StaffUserId");

                    b.ToTable("CheckIns", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<decimal>("BasePricePerHour")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SportCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("SurfaceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SportCenterId")
                        .HasDatabaseName("IX_Courts_SportCenterId");

                    b.HasIndex("SportId")
                        .HasDatabaseName("IX_Courts_SportId");

                    b.HasIndex("SportCenterId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Courts_Center_Code");

                    b.HasIndex("SportCenterId", "SportId", "Status")
                        .HasDatabaseName("IX_Courts_Center_Sport_Status");

                    b.ToTable("Courts", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.CourtBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CourtId", "StartAt", "EndAt")
                        .HasDatabaseName("IX_CourtBlocks_Court_Start_End");

                    b.ToTable("CourtBlocks", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("DeepLink")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead", "CreatedAt")
                        .HasDatabaseName("IX_Notifications_User_Read_CreatedAt");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.OperatingHour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<TimeOnly?>("CloseTime")
                        .HasColumnType("time");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<TimeOnly?>("OpenTime")
                        .HasColumnType("time");

                    b.Property<Guid>("SportCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SportCenterId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("UQ_OperatingHours_Center_Day");

                    b.ToTable("OperatingHours", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.OperatingHourException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<TimeOnly?>("CloseTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<TimeOnly?>("OpenTime")
                        .HasColumnType("time");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("SportCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SportCenterId", "Date")
                        .IsUnique()
                        .HasDatabaseName("UQ_OperatingHourExceptions_Center_Date");

                    b.ToTable("OperatingHourExceptions", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("PaidByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("PaymentKind")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<string>("ProviderTransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("RelatedPaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("TransactionStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("IX_Payments_BookingId");

                    b.HasIndex("ConfirmedByUserId");

                    b.HasIndex("PaidByUserId");

                    b.HasIndex("ProviderTransactionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Payments_ProviderTransactionId")
                        .HasFilter("([ProviderTransactionId] IS NOT NULL)");

                    b.HasIndex("RelatedPaymentId");

                    b.HasIndex("TransactionStatus", "CreatedAt")
                        .HasDatabaseName("IX_Payments_Status_CreatedAt");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.PriceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("PricePerHour")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("CourtId", "DayOfWeek", "IsActive")
                        .HasDatabaseName("IX_PriceRules_Court_Day_Active");

                    b.ToTable("PriceRules", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_RefreshTokens_TokenHash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_UserId_ExpiresAt");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("CustomerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Reviews_BookingId");

                    b.HasIndex("CustomerUserId")
                        .HasDatabaseName("IX_Reviews_CustomerUserId");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.Sport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Sports_Code");

                    b.ToTable("Sports", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.SportCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("Asia/Ho_Chi_Minh");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Ward")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_SportCenters_Status");

                    b.HasIndex("District", "City")
                        .HasDatabaseName("IX_SportCenters_District_City");

                    b.ToTable("SportCenters", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.StaffAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("SportCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StaffUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StaffUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_StaffAssignments_OneActivePerStaff")
                        .HasFilter("([IsActive]=(1))");

                    b.HasIndex("SportCenterId", "IsActive")
                        .HasDatabaseName("IX_StaffAssignments_SportCenterId_IsActive");

                    b.ToTable("StaffAssignments", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<bool>("AllowOutstandingCheckIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("DefaultDepositPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("HoldDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MinBookingLeadMinutes")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("PhoneVerifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_PhoneNumber");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("Platform")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DeviceToken")
                        .IsUnique()
                        .HasDatabaseName("UX_UserDevices_DeviceToken");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("IX_UserDevices_UserId_IsActive");

                    b.ToTable("UserDevices", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BookingNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("PaymentNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PreferredAreaName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("PreferredLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("PreferredLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<bool>("ReminderNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.VerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("Purpose")
                        .HasColumnType("tinyint");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Target", "Purpose", "ExpiresAt")
                        .HasDatabaseName("IX_VerificationCodes_Target_Purpose_ExpiresAt");

                    b.ToTable("VerificationCodes", (string)null);
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.Booking", b =>
                {
                    b.HasOne("CourtGo.Domain.Entities.CancellationPolicy", "CancellationPolicy")
                        .WithMany("Bookings")
                        .HasForeignKey("CancellationPolicyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CourtGo.Domain.Entities.Court", "Court")
                        .WithMany("Bookings")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CourtGo.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedBookings")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CourtGo.Domain.Entities.User", "CustomerUser")
                        .WithMany("CustomerBookings")
                        .HasForeignKey("CustomerUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CancellationPolicy");

                    b.Navigation("Court");

                    b.Navigation("CreatedByUser");

                    b.Navigation("CustomerUser");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.BookingSlot", b =>
                {
                    b.HasOne("CourtGo.Domain.Entities.Booking", "Booking")
                        .WithMany("Slots")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CourtGo.Domain.Entities.Court", "Court")
                        .WithMany("BookingSlots")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CourtGo.Domain.Entities.PriceRule", "PriceRule")
                        .WithMany("BookingSlots")
                        .HasForeignKey("PriceRuleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Booking");

                    b.Navigation("Court");

                    b.Navigation("PriceRule");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.BookingStatusHistory", b =>
                {
                    b.HasOne("CourtGo.Domain.Entities.Booking", "Booking")
                        .WithMany("StatusHistories")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CourtGo.Domain.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Booking");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.CancellationPolicyRule", b =>
                {
                    b.HasOne("CourtGo.Domain.Entities.CancellationPolicy", "CancellationPolicy")
                        .WithMany("Rules")
                        .HasForeignKey("CancellationPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CancellationPolicy");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.CancellationRequest", b =>
                {
                    b.HasOne("CourtGo.Domain.Entities.Booking", "Booking")
                        .WithMany("CancellationRequests")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CourtGo.Domain.Entities.User", "ProcessedByUser")
                        .WithMany()
                        .HasForeignKey("ProcessedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CourtGo.Domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ProcessedByUser");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.CheckIn", b =>
                {
                    b.HasOne("CourtGo.Domain.Entities.Booking", "Booking")
                        .WithOne("CheckIn")
                        .HasForeignKey("CourtGo.Domain.Entities.CheckIn", "BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CourtGo.Domain.Entities.User", "StaffUser")
                        .WithMany()
                        .HasForeignKey("StaffUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("StaffUser");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.Court", b =>
                {
                    b.HasOne("CourtGo.Domain.Entities.SportCenter", "SportCenter")
                        .WithMany("Courts")
                        .HasForeignKey("SportCenterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CourtGo.Domain.Entities.Sport", "Sport")
                        .WithMany("Courts")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sport");

                    b.Navigation("SportCenter");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.CourtBlock", b =>
                {
                    b.HasOne("CourtGo.Domain.Entities.Court", "Court")
                        .WithMany("CourtBlocks")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CourtGo.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.Notification", b =>
                {
                    b.HasOne("CourtGo.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.OperatingHour", b =>
                {
                    b.HasOne("CourtGo.Domain.Entities.SportCenter", "SportCenter")
                        .WithMany("OperatingHours")
                        .HasForeignKey("SportCenterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SportCenter");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.OperatingHourException", b =>
                {
                    b.HasOne("CourtGo.Domain.Entities.SportCenter", "SportCenter")
                        .WithMany("OperatingHourExceptions")
                        .HasForeignKey("SportCenterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SportCenter");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.Payment", b =>
                {
                    b.HasOne("CourtGo.Domain.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CourtGo.Domain.Entities.User", "ConfirmedByUser")
                        .WithMany()
                        .HasForeignKey("ConfirmedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CourtGo.Domain.Entities.User", "PaidByUser")
                        .WithMany()
                        .HasForeignKey("PaidByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CourtGo.Domain.Entities.Payment", "RelatedPayment")
                        .WithMany("RefundPayments")
                        .HasForeignKey("RelatedPaymentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Booking");

                    b.Navigation("ConfirmedByUser");

                    b.Navigation("PaidByUser");

                    b.Navigation("RelatedPayment");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.PriceRule", b =>
                {
                    b.HasOne("CourtGo.Domain.Entities.Court", "Court")
                        .WithMany("PriceRules")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Court");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("CourtGo.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.Review", b =>
                {
                    b.HasOne("CourtGo.Domain.Entities.Booking", "Booking")
                        .WithOne("Review")
                        .HasForeignKey("CourtGo.Domain.Entities.Review", "BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CourtGo.Domain.Entities.User", "CustomerUser")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("CustomerUser");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.StaffAssignment", b =>
                {
                    b.HasOne("CourtGo.Domain.Entities.SportCenter", "SportCenter")
                        .WithMany("StaffAssignments")
                        .HasForeignKey("SportCenterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CourtGo.Domain.Entities.User", "StaffUser")
                        .WithMany("StaffAssignments")
                        .HasForeignKey("StaffUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SportCenter");

                    b.Navigation("StaffUser");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.SystemSetting", b =>
                {
                    b.HasOne("CourtGo.Domain.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.UserDevice", b =>
                {
                    b.HasOne("CourtGo.Domain.Entities.User", "User")
                        .WithMany("UserDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.UserPreference", b =>
                {
                    b.HasOne("CourtGo.Domain.Entities.User", "User")
                        .WithOne("UserPreference")
                        .HasForeignKey("CourtGo.Domain.Entities.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.VerificationCode", b =>
                {
                    b.HasOne("CourtGo.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.Booking", b =>
                {
                    b.Navigation("CancellationRequests");

                    b.Navigation("CheckIn");

                    b.Navigation("Payments");

                    b.Navigation("Review");

                    b.Navigation("Slots");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.CancellationPolicy", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.Court", b =>
                {
                    b.Navigation("BookingSlots");

                    b.Navigation("Bookings");

                    b.Navigation("CourtBlocks");

                    b.Navigation("PriceRules");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.Payment", b =>
                {
                    b.Navigation("RefundPayments");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.PriceRule", b =>
                {
                    b.Navigation("BookingSlots");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.Sport", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.SportCenter", b =>
                {
                    b.Navigation("Courts");

                    b.Navigation("OperatingHourExceptions");

                    b.Navigation("OperatingHours");

                    b.Navigation("StaffAssignments");
                });

            modelBuilder.Entity("CourtGo.Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedBookings");

                    b.Navigation("CustomerBookings");

                    b.Navigation("Notifications");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reviews");

                    b.Navigation("StaffAssignments");

                    b.Navigation("UserDevices");

                    b.Navigation("UserPreference");
                });
#pragma warning restore 612, 618
        }
    }
}
